#pragma once

#define MASTER_LEFT 
#define SPLIT_USB_DETECT
#define TAPPING_TERM 180
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define PMW3320_SCLK_PIN D2
#define PMW3320_SDIO_PIN B6
#define PMW3320_CS_PIN B5 
#define RGBLIGHT_DEFAULT_HUE 59
#define RGBLIGHT_DEFAULT_SAT 100
#define RGBLIGHT_DEFAULT_VAL 3